version: "3.4"
services:
  medalla-validator.dnp.dappnode.eth:
    image: "medalla-validator.dnp.dappnode.eth:1.0.2"
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        - UPSTREAM_VERSION
    volumes:
      - "logs:/var/log"
      - "data:/root/.config/ethereum2/"
      - "db-api:/app/db-api"
    restart: always
    environment:
      - PASSWORD=
      - GRAFFITI=validating_from_DAppNode
      - VERBOSITY=info
      - LOG_LEVEL=
      - EXTRA_OPTS=
volumes:
  data: {}
  db-api: {}
  logs: {}
