version: '3.4'
services:
  prysm-validator.public.dappnode.eth:
    image: 'prysm-validator.public.dappnode.eth:1.0.7'
    build:
      context: ./build
      args:
        - VERSION
    volumes:
      - 'data:/data'
      - 'logs:/var/log'
      - 'keymanager:/keymanager'
    restart: always
    environment:
      - PASSWORD=edu
      - VERBOSITY=info
      - EXTRA_OPTS=--enable-account-metrics
volumes:
  data: {}
  logs: {}
  keymanager: {}
