name: Update DAppNode package

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '00 */4 * * *'
    - cron:  '* * * * *'
jobs:
  dappnodepackage-update:
    name: Trigger the DAppNode Package update
    runs-on: ubuntu-latest
    env: 
      DISPATCH_REPO: dappnode/DAppNodePackage-zinken-validator
      UPSTREAM_REPO_PRYSM: prysmaticlabs/prysm
      UPSTREAM_REPO_LIGHTHOUSE: sigp/lighthouse
    steps:
    - uses: actions/checkout@v2
    - name: Get the prysm tag
      id: get_prysm_tag
      run: |
        PRYSM_UPSTREAM_TAG=$(curl https://api.github.com/repos/$UPSTREAM_REPO_PRYSM/tags | jq .[0].name | tr -d "\"" )
        PRYSM_DNP_UPSTREAM=$(cat docker-compose.yml | grep  UPSTREAM_VERSION: | sed 's/.*UPSTREAM_VERSION: //g')
        if [ $PRYSM_UPSTREAM_TAG != $PRYSM_DNP_UPSTREAM ];then
            echo "::set-output name=trigger_prysm_update::true"
        fi
        echo ::set-output name=TAG::$PRYSM_UPSTREAM_TAG

    - name: update Prysm UPSTREAM_VERSION and commit changes
      if: steps.get_prysm_tag.outputs.trigger_prysm_update == 'true'
      run: |
        sed -i "s/        UPSTREAM_VERSION: .*/        UPSTREAM_VERSION: ${{ steps.get_prysm_tag.outputs.TAG }}/g" docker-compose.yml
        git config --global user.email "eduadiez@gmail.com"
        git config --global user.name "Eduardo"
        git commit -am "Github action bumped prysm version to ${{ steps.get_prysm_tag.outputs.TAG }}"
        git push

    - name: Get the lighthouse tag
      id: get_lighthouse_tag
      run: |
        LIGHTHOUSE_UPSTREAM_TAG=$(curl https://api.github.com/repos/$UPSTREAM_REPO_LIGHTHOUSE/tags | jq .[0].name | tr -d "\"" )
        LIGHTHOUSE_DNP_UPSTREAM=$(cat docker-compose.yml | grep  UPSTREAM_VERSION_LIGHTHOUSE: | sed 's/.*UPSTREAM_VERSION_LIGHTHOUSE: //g')
        if [ $LIGHTHOUSE_UPSTREAM_TAG != $LIGHTHOUSE_DNP_UPSTREAM ];then
            echo "::set-output name=trigger_lighthouse_update::true"
        fi
        echo ::set-output name=TAG::$LIGHTHOUSE_UPSTREAM_TAG

    - name: update Lighthouse UPSTREAM_VERSION and commit changes
      if: steps.get_lighthouse_tag.outputs.trigger_lighthouse_update == 'true'
      run: |
        sed -i "s/        UPSTREAM_VERSION_LIGHTHOUSE: .*/        UPSTREAM_VERSION_LIGHTHOUSE: ${{ steps.get_lighthouse_tag.outputs.TAG }}/g" docker-compose.yml
        git config --global user.email "eduadiez@gmail.com"
        git config --global user.name "Eduardo"
        git commit -am "Github action bumped lighthouse version to ${{ steps.get_lighthouse_tag.outputs.TAG }}"
        git push
    
    - name: dispacth event
      if: steps.get_prysm_tag.outputs.trigger_prysm_update == 'true' || steps.get_lighthouse_tag.outputs.trigger_lighthouse_update == 'true'
      run: |
        curl -v -X POST -u "${{ secrets.PAT_GITHUB }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Content-Type: application/json" \
        --data '{"event_type":"new_release", "client_payload": { "tag":""}}' \
        https://api.github.com/repos/$DISPATCH_REPO/dispatches
